version: '3.9'

volumes:
    logs:
        driver: local

services:
    # Slim app service
    app:
        build:
            context: .
            dockerfile: ./.docker/reactphp/Dockerfile
        container_name: php-app
        working_dir: /app/
        environment:
            docker: "true"
        volumes:
            - .:/app
            - logs:/app/logs
            # - ./.docker/php/custom.ini:/etc/php/8.3/fpm/conf.d/overrides.ini
        depends_on:
            - db
        links:
            - "db:database"
        ports:
            - "8080:8080"

    # Postgres service
    db:
        image: postgres:15-alpine
        container_name: db
        restart: always
        environment:
            POSTGRES_PASSWORD: POSTGRES_PASSWORD
            POSTGRES_DB: backofficeapi
        ports:
            - "5432:5432"

    # Postgres Adminer service
    adminer:
        image: adminer
        restart: always
        ports:
            - 3000:8080

    # Nginx service
    nginx:
        container_name: nginx
        build:
            context: ./.docker/nginx
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./:/app
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/sites/:/etc/nginx/sites-available
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
        depends_on:
            - app
        links:
            - "app:php-fpm"
