version: '3.9'

services:
  roadrunner:
    container_name: roadrunner
    build:
      context: .
      dockerfile: .docker/roadrunner/Dockerfile
      args:
        PHP_IMAGE_VERSION: ${PHP_IMAGE_VERSION}
    ports:
      - 8080:8080
    working_dir: /app/
    volumes:
      - .:/app
      - .docker/roadrunner/conf/rr.yaml:/etc/rr.yaml:ro
    env_file:
      - .docker/roadrunner/conf/rr.env
      - .env
    depends_on:
      - db
    links:
      - "db:database"
    # Postgres service
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: backofficeapi
    ports:
      - "5432:5432"
